package br.com.sistema.mgs.view;

import br.com.sistema.mgs.dao.ClienteDAO;
import br.com.sistema.mgs.dao.ServicoDAO;
import br.com.sistema.mgs.model.Cliente;
import br.com.sistema.mgs.model.LimitaCaracteres;
import br.com.sistema.mgs.model.Servico;
import br.com.sistema.mgs.model.Utilitarios;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmServico extends javax.swing.JFrame {

    Cliente obj = new Cliente();
    ClienteDAO dao = new ClienteDAO();
    Servico objs = new Servico();
    ServicoDAO daos = new ServicoDAO();

    public void listar() {
        ServicoDAO dao = new ServicoDAO();
        List<Servico> lista = dao.listarServicos();
        DefaultTableModel dados = (DefaultTableModel) table_servicos.getModel();
        dados.setNumRows(0);
        for (Servico s : lista) {
            dados.addRow(new Object[]{
                s.getId(),
                s.getCliente().getId(),
                s.getCliente().getNome(),
                s.getEquipamento(),
                s.getMarca(),
                s.getModelo(),
                s.getDescricao(),
                s.getServico_prestado(),
                s.getValor(),
                s.getData_servico()
            });
        }
    }

    public FrmServico() {
        initComponents();
        Utilitarios u = new Utilitarios();
        u.InserirIcone(this);
        codCliente.setDocument(new LimitaCaracteres(100, LimitaCaracteres.TipoEntrada.NUMEROINTEIRO));
        nome.setDocument(new LimitaCaracteres(200, LimitaCaracteres.TipoEntrada.NOME));
        equipamento.setDocument(new LimitaCaracteres(100, LimitaCaracteres.TipoEntrada.NOME));
        marca.setDocument(new LimitaCaracteres(100, LimitaCaracteres.TipoEntrada.NOME));
        valor.setDocument(new LimitaCaracteres(100, LimitaCaracteres.TipoEntrada.NUMERODECIMAL));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        dados_cliente = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        codCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        dados_servico = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        codServico = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        equipamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        servico = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        valor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_servicos = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Serviços Realizados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(202, 202, 202))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        dados_cliente.setBackground(new java.awt.Color(255, 255, 255));
        dados_cliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cliente"));

        jLabel3.setText("*Código:");

        codCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codClienteActionPerformed(evt);
            }
        });
        codCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codClienteKeyPressed(evt);
            }
        });

        jLabel2.setText("*Nome:");

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        btnSearch.setText("Pesquisar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dados_clienteLayout = new javax.swing.GroupLayout(dados_cliente);
        dados_cliente.setLayout(dados_clienteLayout);
        dados_clienteLayout.setHorizontalGroup(
            dados_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dados_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dados_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dados_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dados_clienteLayout.createSequentialGroup()
                        .addComponent(codCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dados_clienteLayout.createSequentialGroup()
                        .addComponent(nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addGap(23, 23, 23))))
        );
        dados_clienteLayout.setVerticalGroup(
            dados_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dados_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dados_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(dados_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)))
        );

        dados_servico.setBackground(new java.awt.Color(255, 255, 255));
        dados_servico.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Serviço"));

        jLabel4.setText("Código:");

        codServico.setEditable(false);
        codServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codServicoActionPerformed(evt);
            }
        });
        codServico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codServicoKeyPressed(evt);
            }
        });

        jLabel5.setText("*Equipamento:");

        jLabel6.setText("Serviço:");

        servico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Instalação", "Manutenção", " " }));

        jLabel7.setText("*Modelo:");

        jLabel8.setText("*Marca:");

        jLabel9.setText("*Descrição:");

        descricao.setColumns(20);
        descricao.setRows(5);
        jScrollPane1.setViewportView(descricao);

        jLabel10.setText("Data:");

        jLabel11.setText("*Valor:");

        data.setEditable(false);

        javax.swing.GroupLayout dados_servicoLayout = new javax.swing.GroupLayout(dados_servico);
        dados_servico.setLayout(dados_servicoLayout);
        dados_servicoLayout.setHorizontalGroup(
            dados_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dados_servicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dados_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dados_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codServico, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dados_servicoLayout.createSequentialGroup()
                        .addGroup(dados_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                            .addComponent(marca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(equipamento, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(dados_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dados_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(servico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(data)
                            .addComponent(valor))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        dados_servicoLayout.setVerticalGroup(
            dados_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dados_servicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dados_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(codServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(dados_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(equipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(servico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(dados_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(dados_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dados_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dados_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(dados_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dados_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(dados_servico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(dados_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dados_servico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dados do Serviço", jPanel2);

        table_servicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.Serviço", "Cod.Cliente", "Nome", "Equipamento", "Modelo", "Marca", "Descrição", "Serviço", "Valor", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_servicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_servicosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_servicos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta Serviço", jPanel3);

        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btnNovo)
                .addGap(60, 60, 60)
                .addComponent(btnSalvar)
                .addGap(60, 60, 60)
                .addComponent(btnEditar)
                .addGap(60, 60, 60)
                .addComponent(btnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codClienteActionPerformed

    private void codClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codClienteKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            obj = new Cliente();
            dao = new ClienteDAO();
            obj = dao.consultaPorCodigo(Integer.parseInt(codCliente.getText()));
            nome.setText(obj.getNome());
        }

    }//GEN-LAST:event_codClienteKeyPressed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        obj = new Cliente();
        dao = new ClienteDAO();
        obj = dao.consultaPorCodigo(Integer.parseInt(codCliente.getText()));
        nome.setText(obj.getNome());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void codServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codServicoActionPerformed

    private void codServicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codServicoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_codServicoKeyPressed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        new Utilitarios().LimpaTela(dados_cliente);
        new Utilitarios().LimpaTela(dados_servico);
        descricao.setText("");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        objs = new Servico();

        if (codCliente.getText().isEmpty() || nome.getText().isEmpty() || equipamento.getText().isEmpty() || marca.getText().isEmpty() || modelo.getText().isEmpty()
                || descricao.getText().isEmpty() || valor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha os campos em branco.");
        } else {
            Cliente c = new Cliente();
            c.setId(Integer.parseInt(codCliente.getText()));
            objs.setCliente(c);
            objs.setEquipamento(equipamento.getText());
            objs.setMarca(marca.getText());
            objs.setModelo(modelo.getText());
            objs.setDescricao(descricao.getText());
            objs.setServico_prestado(servico.getSelectedItem().toString());
            objs.setValor(Double.parseDouble(valor.getText().replaceAll(",", ".")));
            objs.setData_servico(data.getText());
            Date agora = new Date();
            SimpleDateFormat dataEUA = new SimpleDateFormat("yyyy-MM-dd");
            String dataFormatada = dataEUA.format(agora);
            objs.setData_servico(dataFormatada);
            daos = new ServicoDAO();
            daos.cadastrarServicos(objs);
            new Utilitarios().LimpaTela(dados_cliente);
            new Utilitarios().LimpaTela(dados_servico);
            descricao.setText("");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        objs = new Servico();
        Cliente c = new Cliente();
        c.setId(Integer.parseInt(codCliente.getText()));
        objs.setCliente(c);
        objs.setId(Integer.parseInt(codServico.getText()));
        objs.setEquipamento(equipamento.getText());
        objs.setMarca(marca.getText());
        objs.setModelo(modelo.getText());
        objs.setDescricao(descricao.getText());
        objs.setServico_prestado(servico.getSelectedItem().toString());
        objs.setValor(Double.parseDouble(valor.getText().replaceAll(",", ".")));
        objs.setData_servico(data.getText());
        daos = new ServicoDAO();
        daos.editarServico(objs);
        new Utilitarios().LimpaTela(dados_cliente);
        new Utilitarios().LimpaTela(dados_servico);
        descricao.setText("");
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        objs = new Servico();
        objs.setId(Integer.parseInt(codServico.getText()));

        daos = new ServicoDAO();
        daos.excluirServicos(objs);
        new Utilitarios().LimpaTela(dados_cliente);
        new Utilitarios().LimpaTela(dados_servico);
        descricao.setText("");
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void table_servicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_servicosMouseClicked
        jTabbedPane1.setSelectedIndex(0);
        codServico.setText(table_servicos.getValueAt(table_servicos.getSelectedRow(), 0).toString());
        codCliente.setText(table_servicos.getValueAt(table_servicos.getSelectedRow(), 1).toString());
        nome.setText(table_servicos.getValueAt(table_servicos.getSelectedRow(), 2).toString());
        equipamento.setText(table_servicos.getValueAt(table_servicos.getSelectedRow(), 3).toString());
        marca.setText(table_servicos.getValueAt(table_servicos.getSelectedRow(), 4).toString());
        modelo.setText(table_servicos.getValueAt(table_servicos.getSelectedRow(), 5).toString());
        descricao.setText(table_servicos.getValueAt(table_servicos.getSelectedRow(), 6).toString());
        servico.setSelectedItem(String.valueOf(table_servicos.getValueAt(table_servicos.getSelectedRow(), 7).toString()));
        valor.setText(table_servicos.getValueAt(table_servicos.getSelectedRow(), 8).toString());
        data.setText(table_servicos.getValueAt(table_servicos.getSelectedRow(), 9).toString());
    }//GEN-LAST:event_table_servicosMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
        Date agora = new Date();
        SimpleDateFormat dataBr = new SimpleDateFormat("dd/MM/yyyy");
        String dataFormatada = dataBr.format(agora);
        data.setText(dataFormatada);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField codCliente;
    private javax.swing.JTextField codServico;
    private javax.swing.JPanel dados_cliente;
    private javax.swing.JPanel dados_servico;
    private javax.swing.JTextField data;
    private javax.swing.JTextArea descricao;
    private javax.swing.JTextField equipamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField nome;
    private javax.swing.JComboBox<String> servico;
    private javax.swing.JTable table_servicos;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
